-- Benchmark records
CREATE TABLE benchmarks (
    id          integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    year        integer NOT NULL,
    day         integer NOT NULL,
    input       varchar(256) NOT NULL,
    participant varchar(256) NOT NULL,
    language    varchar(256) NOT NULL,
    mean        double precision NOT NULL,
    stddev      double precision NOT NULL,
    median      double precision NOT NULL,
    tuser       double precision NOT NULL,
    tsystem     double precision NOT NULL,
    tmin        double precision NOT NULL,
    tmax        double precision NOT NULL,

    CONSTRAINT single_entry UNIQUE (year, day, input, participant)
);

CREATE INDEX benchmarks_participant_idx ON benchmarks (participant);
